### ISSUE TITLE
Gather a small set of salmon datasets to use across modules

### ISSUE THREAD

**Issue by amoeba** [NCEAS/sasap-training#1]
Because this workshop is oriented towards a particular domain (salmon) and it's so short, it makes sense to try to (1) use salmon data in examples and (2) use as few different datasets as possible across examples.
This should effectively minimize the amount of time we spend explaining datasets because they will be familiar to the group.

Below is a list of each module and either a general description of a list of datasets to use.
Some of these we need to discuss and, once we've decided on something, get it into this repo.

- Literate analysis with R Markdown [1hr]: We've already got the datasets for this
- RStudio and Git/GitHub setup [30 mins]: No datasets needed
- Version control with Git and GitHub [1hr]: Maybe no datasets needed here, unless whoever is doing this module wants to try to integrate one (which I'd recommend to make it more sense).
- Data cleaning and integration
  - Data modeling (tidy data) [30 minutes]: I don't think this module needs any datasets.
  - Cleaning and manipulating data with dplyr [1.5 hr]

    I'm using `dplyr` and `tidyr` for this module.
    Here are the functions I need to teach:

    - dplyr
      - mutate
      - select
      - filter
      - summarise
      - arrange
      - group_by
      - *_join
    - tidyr
      - gather
      - separate
      - reshape

    From this list I can see I need:

    - [ ] Two separate data.frames I can join with. Ideally this is two separate types of data (two different things being measured).
    - [ ] One data.frame I need to reshape (wide <-> tall)
    - [ ] One of these needs to have an obvious grouping variable or two (e.g. year, stock, region)
    - [ ] It's great if some/all of these have extraneous columns
  - Hands on: Clean and integrate 2 data sets in Rmd w/ dplyr [1 hr]
    - [ ] Maybe this module just uses the salmon-y datasets I am looking for above and I use more generic datasets (like built-ins) for the previous module?
- Publication graphics with ggplot [2 hr]
  The above datasets should be sufficient for this.
- Data documentation and publishing [1 hr]
  We should be able to re-use datasets here
- Publishing analyses to the web
  We should be able to re-use datasets here?

**Comment by amoeba** [comment]
Good data join example: Escapement goals and daily escapments to make within-year plots of daily escapement with horizontal bar(s) with the EGs. Good for both data cleaning and plotting

**Comment by amoeba** [comment]
EG data are also a great example of wide data that should be made tall

**Comment by jeanetteclark** [comment]
EG: https://knb.ecoinformatics.org/#view/urn:uuid:1ffd5613-d0d0-4ec8-99b7-774082a938ad

**Comment by jeanetteclark** [comment]
escapement data: https://knb.ecoinformatics.org/#view/urn:uuid:8809a404-f6e1-46a2-91c8-f094c3814b47

**Comment by amoeba** [comment]
This was super helpful, @jeanetteclark, thanks for putting those together.
