### ISSUE TITLE
Build Branching

### ISSUE THREAD

**Issue by jkibele** [NCEAS/sasap-training#11]
First, make a Juneau branch for existing version. Then make an anchorage branch (ANC_WDAFS_2018). Modify build script in each branch to build off of the current branch.

**Comment by jkibele** [comment]
We need to know if we want all available versions (Juneau and Anc_2018 so far) listed under "materials" on the website or just the most current one. Jeanette is discussing this with Matt, right @jeanetteclark ?

**Comment by jeanetteclark** [comment]
okay I'm going to make a call here - let's only have one link for materials but that should be built from the head of the master branch (so no changes in the build script)

Let's retain the Anchorage branch, and update that in the coming weeks with whatever changes we would like to make. Just before the training we can merge the Anchorage branch into master (and tag it). That way the production build isn't building our edits as we go.

Sound reasonable @mbjones?

**Comment by jeanetteclark** [comment]
My thought is that if the changes are small (reflecting mainly instructor style, as opposed to content) we may not need previous versions. But I can see the benefit to both.

**Comment by jkibele** [comment]
So, we decided that one version of the materials was enough. We made a branch, but we keep merging it into master to make travis build everything, so probably didn't really need to do that.
