### ISSUE TITLE
rrtools package

### ISSUE THREAD

**Issue by cornejotux** [NCEAS/sasap-training#13]
In chapter 4, numeral 4.6, it give an example of using "rrtools" to organize a directory for a standard reproducible research structure. Nevertheless, "rrtools" is not on the packages to install in Numeral 3.6.

Should I add it to get it installed?

**Comment by cornejotux** [comment]
Also: 
> install.packages("rrtools")
Installing package into ‘C:/Users/cornejo/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rrtools’ is not available (for R version 3.5.0)

**Comment by cornejotux** [comment]
It is in github:
# install.packages("devtools")
devtools::install_github("benmarwick/rrtools")

**Comment by cornejotux** [comment]
Also, in windows this fails:

rrtools::use_compendium("sasap_training")

Error: 'sasap_training' is not a valid package name. It should: * Contain only ASCII letters, numbers, and '.' * Have at least two characters * Start with a letter * Not end with '.'

**Comment by cornejotux** [comment]
In my VM Windows:
If I do "rrtools::use_compendium("sasap_training")"

The commands fails and RStudio crashes.

**Comment by jeanetteclark** [comment]
uh oh. @amoeba if I'm correct, I don't think we ever got this far in the training. We sort of hand-waved this, but didn't live code it. The code ran fine for me. I would add the code to install this package in the chunk (devtools::install_github("benmarwick/rrtools"), but we should not include it as a pre-requisite

**Comment by jeanetteclark** [comment]
whats the advantage of `remotes` over `devtools`?

**Comment by amoeba** [comment]
remotes doesn't install any dependencies when installed whereas devtools take forever to install because it has some that are slow to install

**Comment by amoeba** [comment]
(so remotes installs fast)

**Comment by jeanetteclark** [comment]
updated training to include a commented out install call in that chunk
