### ISSUE TITLE
Chapter 9.

### ISSUE THREAD

**Issue by cornejotux** [NCEAS/sasap-training#16]
In Chapter 9, numeral 9.5, after the first plot the paragraph is:

`What makes ggplot really powerful is how quickly we can make this plot visualize more aspects of our data. Coloring each point by class (**compact, van, pickup, etc**.) is just a quick extra bit of code:`

The text in bold seem to come from an example using the *cars* data, it should be updated to examples of *Fishing Gear*.

**Comment by jeanetteclark** [comment]
@MadJovanovich make sure you address this when you edit this section

**Comment by MadJovanovich** [comment]
Will definitely use fishing gear, thanks for finding that @cornejotux. I'll start looking at materials today.
