### ISSUE TITLE
dplyr lesson: KNB download fails on IE11

### ISSUE THREAD

**Issue by mbjones** [NCEAS/sasap-training#5]
KNB downloads uisng the 'Download' button just produced a spinning cursor,and no download. Switching to Firefox allows it to work.

**Comment by amoeba** [comment]
Thanks for filing this @mbjones. I filed an issue on the metacatui repo https://github.com/NCEAS/metacatui/issues/409

Did you envision us making any changes to this repo as a result of this? Adding a note about IE11?

**Comment by amoeba** [comment]
Lauren fixed this in MetacatUI and deployed the patched version to various MNs.
