### ISSUE TITLE
dplyr lesson: KNB download fails in read.csv on windows

### ISSUE THREAD

**Issue by mbjones** [NCEAS/sasap-training#6]
Windows R `read.csv()` does not seem to support downloading SSL files directly, but it works on Mac.  Alternative is to download the file with curl, then feed that into read.csv.  See discussion on https://stackoverflow.com/questions/4125788/reading-csv-files-over-ssl-with-r .

**Comment by amoeba** [comment]
Thanks for filing this @mbjones . Did you envision us making a change to this repo, like editing a lesson? I can do that.

**Comment by mbjones** [comment]
Yes, I think we should provide a workaround for users on windows from whom read.csv() does not function with SSL URLs.  It seems that using RCurl and then passing the output of the download to read.csv() works in all cases.  See https://stackoverflow.com/questions/4125788/reading-csv-files-over-ssl-with-r for several alternatives.

**Comment by amoeba** [comment]
Thanks for the link. I don't really like any of those alternatives. I was thinking of just saying "if you have issues, download the file manually". I guess you'd prefer a single line of code that works on all platforms?

**Comment by amoeba** [comment]
Just tested this out on a Win10 VM: This gets even crazier. The first time, I get `InternetOpenURL failed: 'A certificate is required to complete client authentication'`. If I run it a second time, it succeeds.

**Comment by amoeba** [comment]
Did some testing, seems like `read.csv(url({the url}, method = "libcurl"))` works. I've made those fixes in the appropriate places. Wrapping the URL in a call to `url` allows the http request to be done via libcurl instead of falling back to the OS-level functionality in Win10 which doesn't work here.
