### ISSUE TITLE
RStudio Version in RStudio Setup Module

### ISSUE THREAD

**Issue by jkibele** [NCEAS/sasap-training#8]
Version `1.1.383` is hard coded into the [page](https://github.com/NCEAS/sasap-training/blob/master/materials/reproducible-analysis-in-r/02-setup-rstudio-git-github.Rmd) as the version to look for (and update if different). Should we change this? ...or should we change the wording to suggest a minimum version?

**Comment by cornejotux** [comment]
Version 1.1.447 is the one that I installed yesterday. 
I just check it and it is the latest version. 
I will confirm that there are no problem with this version tomorrow, when I'm done for doing the whole book step by step under this (1.1.447) version.

**Comment by jeanetteclark** [comment]
changed this to the latest version
